export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';
export const SET_PROJECT = 'SET_PROJECT';
export const GET_CONTRIBUTORS = 'GET_CONTRIBUTORS';
export const GET_CONTRIBUTORS_SUCCESS = 'GET_CONTRIBUTORS_SUCCESS';
export const GET_CONTRIBUTORS_FAIL = 'GET_CONTRIBUTORS_FAIL';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

